// design06 Details — редактируемый слой (Approach A2): на элемент одна запись, ключ = data-eid.
// Единственный источник правды для позиции/размера/поворота/типографики; редактор патчит поля и пишет сюда.
import type { El } from "../layout";

export const layout: Record<string, El> = {
  "details/0": { raw: { "backgroundColor": "rgb(255, 255, 255)" } },
  "details/1": { w: 1776, h: 1554, raw: { "alignItems": "center" } },
  "details/2": { w: 1776, h: 1554, raw: { "backgroundColor": "rgb(255, 255, 255)" } },
  "details/3": { w: 1776, h: 1554 },
  "details/4": { raw: { "background": "rgb(255, 255, 255)" } },
  "details/bg-photo": { w: 3273.8, h: 2398.06, x: -748.901, y: -136.932, rot: 90 },
  "details/6": { w: 1465.2, h: 1243.2, raw: { "position": "absolute", "top": "155.4px", "left": "155.4px" } },
  "details/title": { w: 805.354, h: 101.933, x: 485.323, y: 73.9978, raw: { "touchAction": "pan-x pan-y pinch-zoom" } },
  "details/8": { w: 805.354, h: 101.933, raw: { "writingMode": "horizontal-tb" } },
  "details/9": { x: 0, y: -8.53333 },
  "details/title-text": { font: "YACkoFu1RUU_0, auto", fontSize: 85.3333, color: "rgb(53, 80, 116)", lineHeight: "119px", letterSpacing: "0em", textTransform: "uppercase", raw: { "--gixK-A": "0", "--kJ5CrQ": "0", "--zPlnxA": "none", "listStyleType": "none" } },
  "details/11": { color: "rgb(53, 80, 116)", raw: { "fontSize": "1em", "fontWeight": "700", "fontStyle": "normal", "fontKerning": "none", "textDecorationLine": "none", "textDecorationThickness": "initial", "textDecorationStyle": "initial" } },
  "details/accommodation-heading": { w: 411.156, h: 66.8, x: 233.932, y: 202.694, raw: { "touchAction": "pan-x pan-y pinch-zoom" } },
  "details/13": { w: 411.156, h: 66.8, raw: { "writingMode": "horizontal-tb" } },
  "details/14": { x: 0, y: -5.6 },
  "details/accommodation-heading-text": { font: "YAFcfgcNhWk_3, auto", fontSize: 56, color: "rgb(53, 80, 116)", lineHeight: "78px", letterSpacing: "0em", textTransform: "none", raw: { "--gixK-A": "0", "--kJ5CrQ": "0", "--zPlnxA": "none", "listStyleType": "none" } },
  "details/16": { color: "rgb(53, 80, 116)", raw: { "fontSize": "1em", "fontWeight": "400", "fontStyle": "normal", "fontKerning": "normal", "textDecorationLine": "none", "textDecorationThickness": "initial", "textDecorationStyle": "initial" } },
  "details/17": { color: "rgb(53, 80, 116)", raw: { "fontSize": "1em", "fontWeight": "400", "fontStyle": "normal", "fontKerning": "normal", "textDecorationLine": "none", "textDecorationThickness": "initial", "textDecorationStyle": "initial" } },
  "details/accommodation-paragraph": { w: 1312.41, h: 300.8, x: 233.932, y: 275.122, raw: { "touchAction": "pan-x pan-y pinch-zoom" } },
  "details/19": { w: 1312.41, h: 300.8, raw: { "writingMode": "horizontal-tb" } },
  "details/20": { x: 0, y: -5.6 },
  "details/accommodation-paragraph-text": { font: "YAFcfgcNhWk_3, auto", fontSize: 56, color: "rgb(53, 80, 116)", lineHeight: "78px", letterSpacing: "0em", textTransform: "none", raw: { "--gixK-A": "0", "--kJ5CrQ": "0", "--zPlnxA": "none", "listStyleType": "none" } },
  "details/22": { color: "rgb(53, 80, 116)", raw: { "fontSize": "1em", "fontWeight": "300", "fontStyle": "normal", "fontKerning": "normal", "textDecorationLine": "none", "textDecorationThickness": "initial", "textDecorationStyle": "initial" } },
  "details/transportation-heading": { w: 364, h: 66.8, x: 233.932, y: 608.6, raw: { "touchAction": "pan-x pan-y pinch-zoom" } },
  "details/24": { w: 364, h: 66.8, raw: { "writingMode": "horizontal-tb" } },
  "details/25": { x: 0, y: -5.6 },
  "details/transportation-heading-text": { font: "YAFcfgcNhWk_3, auto", fontSize: 56, color: "rgb(53, 80, 116)", lineHeight: "78px", letterSpacing: "0em", textTransform: "none", raw: { "--gixK-A": "0", "--kJ5CrQ": "0", "--zPlnxA": "none", "listStyleType": "none" } },
  "details/27": { color: "rgb(53, 80, 116)", raw: { "fontSize": "1em", "fontWeight": "400", "fontStyle": "normal", "fontKerning": "none", "textDecorationLine": "none", "textDecorationThickness": "initial", "textDecorationStyle": "initial" } },
  "details/28": { color: "rgb(53, 80, 116)", raw: { "fontSize": "1em", "fontWeight": "400", "fontStyle": "normal", "fontKerning": "none", "textDecorationLine": "none", "textDecorationThickness": "initial", "textDecorationStyle": "initial" } },
  "details/transportation-paragraph": { w: 1312.41, h: 378.8, x: 231.796, y: 681.4, raw: { "touchAction": "pan-x pan-y pinch-zoom" } },
  "details/30": { w: 1312.41, h: 378.8, raw: { "writingMode": "horizontal-tb" } },
  "details/31": { x: 0, y: -5.6 },
  "details/transportation-paragraph-text": { font: "YAFcfgcNhWk_3, auto", fontSize: 56, color: "rgb(53, 80, 116)", lineHeight: "78px", letterSpacing: "0em", textTransform: "none", raw: { "--gixK-A": "0", "--kJ5CrQ": "0", "--zPlnxA": "none", "listStyleType": "none" } },
  "details/33": { color: "rgb(53, 80, 116)", raw: { "fontSize": "1em", "fontWeight": "300", "fontStyle": "normal", "fontKerning": "normal", "textDecorationLine": "none", "textDecorationThickness": "initial", "textDecorationStyle": "initial" } },
  "details/engraving": { w: 571.622, h: 384.573, x: 205, y: 1149.03, raw: { "touchAction": "pan-x pan-y pinch-zoom" } },
  "details/engraving-photo": { w: 571.622, h: 384.573, x: 0, y: 0, rot: 0 },
  "details/36": { h: 384.573, w: 571.622, scale: 1, raw: { "position": "absolute", "top": "0px", "left": "0px", "transformOrigin": "0px 0px", "pointerEvents": "none" } },
  "details/37": { w: 1776, h: 1554, raw: { "margin": "0px" } },
};
