// design06 baseline sections, in page order. Generated by tools/design06-gen-sections.mjs.
import Hero from "./Hero";
import Calendar from "./Calendar";
import Timeline from "./Timeline";
import Details from "./Details";
import Attire from "./Attire";
import Gift from "./Gift";
import Journey from "./Journey";
import Rsvp from "./Rsvp";
import Closing from "./Closing";

export const DESIGN06_SECTIONS = [Hero, Calendar, Timeline, Details, Attire, Gift, Journey, Rsvp, Closing] as const;
