import puppeteer from 'puppeteer-core';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const b=await puppeteer.launch({executablePath:CHROME, headless:'new', args:['--no-sandbox','--disable-gpu','--hide-scrollbars']});
const p=await b.newPage();
await p.setViewport({width:440,height:6200,deviceScaleFactor:2});
await p.goto('https://lysfilter.my.canva.site/design06/#page-0',{waitUntil:'networkidle2',timeout:90000});
await new Promise(r=>setTimeout(r,6000));
await p.screenshot({path:'refs/ref-render/page0_tall.png'});
const fs=await import('fs'); console.log('size',fs.statSync('refs/ref-render/page0_tall.png').size);
await b.close();
