// design06 baseline sections, in page order. Generated by tools/design06-gen-sections.mjs.
// ВНИМАНИЕ: Survey добавлен вручную (раздел без Canva-эталона) — при ре-генерации
// этого файла не потерять его (импорт + позицию после Journey).
import type { ComponentType } from "react";
import Hero from "./Hero";
import Calendar from "./Calendar";
import Timeline from "./Timeline";
import Details from "./Details";
import Attire from "./Attire";
import Gift from "./Gift";
import Journey from "./Journey";
import Survey from "./Survey"; // раздел БЕЗ Canva-эталона: живой опрос RSVP, скрыт под ?baseline
import Closing from "./Closing";

// Canva-эталон анкеты (Rsvp.tsx/Rsvp.layout.ts) заменён живым Survey и удалён.
export const DESIGN06_SECTIONS = [
  Hero,
  Calendar,
  Timeline,
  Details,
  Attire,
  Gift,
  Journey,
  Survey,
  Closing,
] as const;

// Слаги секций в ТОМ ЖЕ порядке, что DESIGN06_SECTIONS: i-я section.rGeu6w в DOM == SECTION_SLUGS[i].
// Слаг == префикс data-eid секции (sectionOf в editor/registry.ts) — им и слой additions, и
// редактор адресуют секцию-владельца.
export const SECTION_SLUGS = [
  "hero", "calendar", "timeline", "details", "attire", "gift", "journey", "survey", "closing",
] as const;

// Карта slug → компонент: Design07 рендерит секции ПО МАНИФЕСТУ (sectionManifest.ts) через неё,
// что даёт порядок/скрытие/добавление секций как данные. Дефолтный манифест == этот же порядок.
export const SECTION_COMPONENTS: Record<string, ComponentType> = {
  hero: Hero,
  calendar: Calendar,
  timeline: Timeline,
  details: Details,
  attire: Attire,
  gift: Gift,
  journey: Journey,
  survey: Survey,
  closing: Closing,
};
